version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    env_file: ./.env
    ports:
      - 6883:6883
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - mysql-data:/var/lib/mysql

  nodeserver:
    depends_on:
      - db
    build: ./
    env_file: ./.env
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HOST=db
    stdin_open: true
    tty: true
    container_name: nodeserver
    ports:
      - 3000:3000
    restart: always

volumes:
  mysql-data: